DROP TABLE IF EXISTS inventory;
CREATE TABLE inventory (
  value INTEGER NOT NULL
);

DROP TABLE IF EXISTS product;
CREATE TABLE product (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  productName TEXT NOT NULL,
  price INTEGER NOT NULL,
  quantity INTEGER NOT NULL,
  added TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);